import Header from "../_components/header";
import Sidebar from "../_components/sidebar";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-row p-4 h-screen">
        <Sidebar />

        <main className="w-4/5 p-1">
          <header>
            <Header />
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
